//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetResponder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpExpensesTable
    {
        public string C_MP_s_Name { get; set; }
        public string C_Details { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public long PrimaryTransactionID { get; set; }
        public float Amount_ClaimedReal { get; set; }
        public byte FunnyTag { get; set; }
        public bool TweetedTag { get; set; }
        public System.DateTime RealDate { get; set; }
        public string C_MP_s_Twitter { get; set; }
    }
}
